# Generated by Django 3.2.14 on 2022-11-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cac', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_dni',
            field=models.CharField(default='dni', max_length=10),
        ),
    ]
